language: node_js
node_js:
  - "7"
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: "build"
  target_branch: "gh-pages"
  on:
    branch: master
